---
- name: Install Jenkins on Amazon Linux
  hosts: all
  become: yes
  tasks:
    - name: Install Java (Jenkins dependency)
      yum:
        name: java-1.8.0-openjdk
        state: present

    - name: Add Jenkins repository
      yum_repository:
        name: jenkins
        description: Jenkins Stable Repo
        baseurl: https://pkg.jenkins.io/redhat/jenkins-2.263.4-1.1.noarch.rpm
        gpgcheck: yes
        gpgkey: https://pkg.jenkins.io/redhat/jenkins.io.key
        enabled: yes

    - name: Install Jenkins
      yum:
        name: jenkins
        state: present

    - name: Start Jenkins service
      service:
        name: jenkins
        state: started
        enabled: yes

    - name: Open Jenkins port in firewall
      firewalld:
        service: http
        permanent: yes
        state: enabled
        immediate: yes

    - name: Open Jenkins port 8080 in firewalld
      firewalld:
        port: 8080/tcp
        permanent: yes
        state: enabled
        immediate: yes
